num = int(input('Digite um número inteiro para que seja feita suaa tabuada: '))

print('O número digitado foi {}. A sua tabuada será: '. format(num))
print("{}x0={}" .format(num, num*0))
print("{}x1={}" .format(num, num*1))
print("{}x2={}" .format(num, num*2))
print("{}x3={}" .format(num, num*3))
print("{}x4={}" .format(num, num*4))
print("{}x5={}" .format(num, num*5))
print("{}x6={}" .format(num, num*6))
print("{}x7={}" .format(num, num*7))
print("{}x8={}" .format(num, num*8))
print("{}x9={}" .format(num, num*9))
print("{}x10={}" .format(num, num*10))